Train UPTRec
[Train] Preparing Clustering:
 88%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉                      | 38/43 [00:01<00:00, 17.89it/s]
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:02<00:00, 21.36it/s]
  0%|                                                                                                                                                                                                        | 0/1 [00:00<?, ?it/s]
Model Training
rec dataset length: 43
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.74s/it]





100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 43/43 [00:12<00:00,  3.58it/s]
Traceback (most recent call last):
  File "main.py", line 269, in <module>
    main()
  File "main.py", line 234, in main
    trainer.train(epoch)
  File "/home/seongbeom/paper/preference_rec/trainers.py", line 99, in train
    self.iteration(epoch, self.train_dataloader, self.cluster_dataloader)
  File "/home/seongbeom/paper/preference_rec/trainers.py", line 536, in iteration
    "Align_loss": "{:.6f}".format(align_losses / len(rec_cf_data_iter)),
UnboundLocalError: local variable 'align_losses' referenced before assignment