Traceback (most recent call last):
  File "main.py", line 267, in <module>
    main()
  File "main.py", line 223, in main
    args = wandb.args
AttributeError: module 'wandb' has no attribute 'args'